name: animated_notification
description: "A customizable Flutter package for displaying animated, dismissible in-app notifications."
version: 1.0.0
repository: https://github.com/Mahmoud-Saeed-Mahmoud/animated_notification
issue_tracker: https://github.com/Mahmoud-Saeed-Mahmoud/animated_notification/issues
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
